services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: macads_backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=12345678abc
      - UPLOAD_DIR=/app/uploads
      - OPENAI_API_KEY=sk-proj-52tT65-c5qR6967-6868-4545-8989-898989898989
      - LANGFUSE_SECRET_KEY=sk-lf-54c0cf35-9730-46d3-bdfd-8ed2c877bcba
      - LANGFUSE_PUBLIC_KEY=pk-lf-3f829d32-e67d-40bc-8516-ab61213cdee8
      - LANGFUSE_HOST=https://us.cloud.langfuse.com
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: macads_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend


